[2024-09-27 13:45:28,796] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.71.254:8000
[2024-09-27 13:45:28,796] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-09-27 13:45:30,579] 63 root - INFO - Dataframe Gathered
[2024-09-27 13:45:30,661] 838 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Varun\Music\Python\ProjectOne\app.py", line 33, in predict_datapoint
    result = (pred[1][1])
              ~~~~^^^
IndexError: index 1 is out of bounds for axis 0 with size 1
[2024-09-27 13:45:30,663] 97 werkzeug - INFO - 127.0.0.1 - - [27/Sep/2024 13:45:30] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
